import React from 'react';
import PropTypes from 'prop-types';

export default class RedemptionCodesEdit extends React.Component {
	static propTypes = {
		catalogEntry: PropTypes.object.isRequired,
		onValueChange: PropTypes.func
	}

	//static FIELD_NAME = '';

	constructor (props) {
		super(props);

		this.state = { value: props.catalogEntry.Title };
	}

	onChange = (val) => {

	}

	render () {
		// TODO: Implement editing these, right now they are only generated by the server on course creation

		return (<div/>);
	}
}
